% Quick script to get basic statistics from energy decay tests,
% rather than running CorrCheck and loglogcorf a bajillion times
% Requirements: angle files with indices 0-9 (missing files are ok), and
% stats files generated by makeallstats with indices 0-9
% Dependencies: hwils
% Nathan Wei, August 2015

clear all;
trials = 10.0; % number of tests carried out
folder = fileparts('/Users/kevin/Documents/Data/data07_31_15/');
addpath(folder);
mean_rmsd = zeros(trials,1); % mean RMSD for a given trial
L = zeros(trials,1); % integral length scale for a given trial
Re = zeros(trials,1); % turbulence Reynolds number for a given trial
epsilon = zeros(trials,1);
nu = 1.46e-5; % kinematic viscosity of air
sum_rmsd = 0;
total_angle_files = trials;
%{
% Compute average RMSD of angles from angle files
for f = 0 : (trials - 1)
    try
        % CHANGE THIS: load angle file for test #f
        filestring1 = strcat('angles_g3g3_0731_0', num2str(f), '.txt');
        A = load(filestring1);
    catch err
        % file does not exist, so skip it and move on to the next one
        total_angle_files = total_angle_files - 1; % decrement counter
        continue;
    end
    % set up parameters
    size = size(A);
    time = size(1);
    avgangle = zeros(time,1); % stores average angle of each timeslice
    rmsd = zeros(time,1); % stores rmsd of each timeslice
    % Get mean angle of each timeslice
    for t = 1 : time
        timeslice = A(t,:);
        avgangle(t) = mean(timeslice);
    end
    % Get RMSD of each timeslice
    for t = 1 : time
        agrid = transpose(reshape(A(t,:),13,11));
        for i = 1 : 11
            for j = 1 : 13
                rmsd(t) = rmsd(t) + (agrid(i,j)-avgangle(t))^2 / 143;
            end
        end
        rmsd(t) = sqrt(rmsd(t));
    end
    mean_rmsd(f+1) = mean(rmsd);
    sum_rmsd = sum_rmsd + mean_rmsd(f+1); % get average by adding all rmsds
    fprintf('Mean RMSD of file %d = %.4f \n', f, mean_rmsd(f+1));
    clear size;
end
fprintf('Average RMSD for this run = %.4f \n', sum_rmsd/total_angle_files);
%}
% Calculating integral length scale and Reynolds number approximation
% If stats files do not exist, this code block will make them
for f = 0 : (trials - 1)
    % CHANGE THIS (should correspond to same test as angle files)
    filestring2 = strcat('statscorr_g3g3_0731_0', num2str(f), '.mat');
    load(filestring2, 'MASvss', 'MASC', 'sepval'); % std/rms, corr, ?
    fprintf('RMS velocity for file %d (m/s) = %.8f \n', f, MASvss);
    % calculate integral length scale
    L(f+1) = hwils(MASC, sepval, 2); %this is the integral length scale
    fprintf('Integral length scale for file %d (m) = %.8f \n', f, L(f+1));
    % calculate energy dissipation
    epsilon(f+1) = 0.5 * (MASvss^3) / L(f+1); % 0.5 is constant prefactor
    % calculate Kolmogorov length scale
    eta(f+1) = (nu^0.75) * (epsilon(f+1)^(-0.25));
    % calculate maximum frequency
    freq(f+1) = MASvss/eta(f+1);
    fprintf('Energy dissipation rate for file %d (W) = %.8f \n', f, epsilon(f+1));
    fprintf('Kolmogorov length scale for file %d (m) = %.8f \n', f, eta(f+1));
    fprintf('Maximum fluctuation frequency for file %d (Hz) = %.8f \n', f, freq(f+1));
    % calculate the taylor microscale (needed to find reynolds number)
    count = 0; 
    n = 2;
    for i=1:length(MASC)
        if(MASC(i) < 0 ) 
            count = count + 1;
        end;
        if(count >= n)
            cutoff = i; 
            break;
        end;

    end;
    MASCc = MASC(1: cutoff); % the cut off structure function
    sepvalc = sepval(1:cutoff); %the cut off sepval 
    figure(1);
    set(gca, 'fontsize', 12);
    plot(sepvalc/L(f+1),MASCc,'b');
    hold on;
    samplePoints = 5:30; % make a vector of the first 26 points excluding noise
    samplePoints2 = sepvalc(samplePoints)/L(f+1);
    curvePoints = 1:1000; % vector used for plotting the quadratic fit
    curvePoints = sepvalc(curvePoints)/L(f+1);
    corrVals = MASCc(samplePoints); % correlation value of the 26 sample points
    plot(samplePoints2,corrVals,'-ok'); % plot these 26 points
    hold on;
    p = polyfit(samplePoints2,corrVals',2); %fit a second order polynomial to these 26 points. Note polyfit wanted both vectors to be row vectors, I transpose corrVals
    y1 = polyval(p,curvePoints);
    plot(curvePoints,y1,'r'); % plot the curve fit
    fprintf('Integral Length Scale = %f\n', L(f+1));
    % the x-intercept of polyfit p is the taylor length scale
    taylorL = max(roots(p))*L(f+1);
    fprintf('The Taylor length scale = %f\n', taylorL);
    fprintf('Comment: I multipled by L because of the scaling of the graph\n');
    %calculated turbulent Reynolds Number
    Re(f+1) = MASvss*taylorL/nu;
    fprintf('mu = %f\nrms = %f\nTurbulent Reynolds Number = %f\n',nu, MASvss, Re(f+1));
    hax = gca; 
    ylabel('correlation   ');
    xlabel('distance (m/L)  ');
    xlim([0 4]);
    ylim([0 1]);
    %title('Correlation Function loglog');
    title('Correlation Function');
end
fprintf('Integral Length Scale range for this run: %.4f to %.4f \n', min(L), max(L));
fprintf('Reynolds Number range for this run: %.4f to %.4f\n', min(Re), max(Re));

rmpath(folder);